set( CCTFTPSERVER_VERSION_MAJOR   0   )
set( CCTFTPSERVER_VERSION_MINOR   0   )
set( CCTFTPSERVER_VERSION_PATCH   1   )
set( CCTFTPSERVER_VERSION_BUILD   0   )
set( CCTFTPSERVER_VERSION_CMAKE ${CCTFTPSERVER_VERSION_MAJOR}.${CCTFTPSERVER_VERSION_MINOR}.${CCTFTPSERVER_VERSION_PATCH})

set( PROJECT_DESCRIPTION    "Tftp Server Project." )